name: Secrets Rotation

on:
  schedule:
    - cron: '0 0 1 1 *'

  # Allows this workflow to be manually run from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ssh-secret-rotation:
    runs-on: ubuntu-latest

    steps:
      - uses: google/secrets-sync-action@v1.4.1
        with:
          SECRETS: |
            ^SECRET$
          REPOSITORIES: |
            ${{github.repository}}
          DRY_RUN: false
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          CONCURRENCY: 10
